version: "3"
services:
  food_server:
    container_name: food_server
    build: ./food
#    ports:
#      - "50051:50051"
    volumes:
      - ./food:/go/src/food/
    command: >
      sh -c "reflex -s -r '\.go$$' go run main.go"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: food_data
      DB_HOST: db
      DB_PORT: 3306

  menu_server:
    container_name: menu_server
    build: ./menu
#    ports:
#      - "50050:50050"
    volumes:
      - ./menu:/go/src/menu/
    command: >
      sh -c "reflex -s -r '\.go$$' go run main.go"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: food_data
      DB_HOST: db
      DB_PORT: 3306

  store_server:
    build: ./store
    ports:
      - "80:80"
    volumes:
      - ./store:/go/src/store/
    command: >
      sh -c "reflex -s -r '\.go$$' go run main.go"
    environment:
      FOOD_HOST: food_server
      FOOD_PORT: 50051
      MENU_HOST: menu_server
      MENU_PORT: 50050

  mysql:
    container_name: db
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: food_data
#    ports:
#      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf_d:/etc/mysql/conf.d"
      - "./mysql/init:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=admin
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - 8888:80