// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.17.3
// source: food/foodpb/food.proto

package foodpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Food struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protein float64 `protobuf:"fixed64,3,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat     float64 `protobuf:"fixed64,4,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs   float64 `protobuf:"fixed64,5,opt,name=carbs,proto3" json:"carbs,omitempty"`
}

func (x *Food) Reset() {
	*x = Food{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Food) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Food) ProtoMessage() {}

func (x *Food) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Food.ProtoReflect.Descriptor instead.
func (*Food) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{0}
}

func (x *Food) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Food) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *Food) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *Food) GetCarbs() float64 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

type CreateFoodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Food *Food `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
}

func (x *CreateFoodRequest) Reset() {
	*x = CreateFoodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFoodRequest) ProtoMessage() {}

func (x *CreateFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFoodRequest.ProtoReflect.Descriptor instead.
func (*CreateFoodRequest) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFoodRequest) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

type CreateFoodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateFoodResponse) Reset() {
	*x = CreateFoodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFoodResponse) ProtoMessage() {}

func (x *CreateFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFoodResponse.ProtoReflect.Descriptor instead.
func (*CreateFoodResponse) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{2}
}

type ReadFoodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FoodId string `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
}

func (x *ReadFoodRequest) Reset() {
	*x = ReadFoodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFoodRequest) ProtoMessage() {}

func (x *ReadFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFoodRequest.ProtoReflect.Descriptor instead.
func (*ReadFoodRequest) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFoodRequest) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

type ReadFoodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Food *Food `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
}

func (x *ReadFoodResponse) Reset() {
	*x = ReadFoodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFoodResponse) ProtoMessage() {}

func (x *ReadFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFoodResponse.ProtoReflect.Descriptor instead.
func (*ReadFoodResponse) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFoodResponse) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

type UpdateFoodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Food *Food `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
}

func (x *UpdateFoodRequest) Reset() {
	*x = UpdateFoodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFoodRequest) ProtoMessage() {}

func (x *UpdateFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFoodRequest.ProtoReflect.Descriptor instead.
func (*UpdateFoodRequest) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFoodRequest) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

type UpdateFoodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Food *Food `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
}

func (x *UpdateFoodResponse) Reset() {
	*x = UpdateFoodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFoodResponse) ProtoMessage() {}

func (x *UpdateFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFoodResponse.ProtoReflect.Descriptor instead.
func (*UpdateFoodResponse) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFoodResponse) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

type DeleteFoodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FoodId string `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
}

func (x *DeleteFoodRequest) Reset() {
	*x = DeleteFoodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFoodRequest) ProtoMessage() {}

func (x *DeleteFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFoodRequest.ProtoReflect.Descriptor instead.
func (*DeleteFoodRequest) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFoodRequest) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

type DeleteFoodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFoodResponse) Reset() {
	*x = DeleteFoodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFoodResponse) ProtoMessage() {}

func (x *DeleteFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFoodResponse.ProtoReflect.Descriptor instead.
func (*DeleteFoodResponse) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{8}
}

type ListFoodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FoodId string `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
}

func (x *ListFoodRequest) Reset() {
	*x = ListFoodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodRequest) ProtoMessage() {}

func (x *ListFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodRequest.ProtoReflect.Descriptor instead.
func (*ListFoodRequest) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{9}
}

func (x *ListFoodRequest) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

type ListFoodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Food *Food `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
}

func (x *ListFoodResponse) Reset() {
	*x = ListFoodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_foodpb_food_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodResponse) ProtoMessage() {}

func (x *ListFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_foodpb_food_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodResponse.ProtoReflect.Descriptor instead.
func (*ListFoodResponse) Descriptor() ([]byte, []int) {
	return file_food_foodpb_food_proto_rawDescGZIP(), []int{10}
}

func (x *ListFoodResponse) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

var File_food_foodpb_food_proto protoreflect.FileDescriptor

var file_food_foodpb_food_proto_rawDesc = []byte{
	0x0a, 0x16, 0x66, 0x6f, 0x6f, 0x64, 0x2f, 0x66, 0x6f, 0x6f, 0x64, 0x70, 0x62, 0x2f, 0x66, 0x6f,
	0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5c,
	0x0a, 0x04, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x74, 0x65, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x74, 0x65, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x03, 0x66, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x62, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x61, 0x72, 0x62, 0x73, 0x22, 0x33, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x04, 0x66, 0x6f, 0x6f,
	0x64, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x46,
	0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6f,
	0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x6f,
	0x64, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6f, 0x6f, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x6f, 0x6f,
	0x64, 0x52, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x22, 0x33, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04,
	0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x22, 0x34, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x04, 0x66, 0x6f,
	0x6f, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6f, 0x6f, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x6f, 0x64, 0x49, 0x64,
	0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f,
	0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6f, 0x6f,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x6f, 0x64,
	0x49, 0x64, 0x22, 0x32, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x6f, 0x6f, 0x64,
	0x52, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x32, 0xcd, 0x02, 0x0a, 0x0b, 0x46, 0x6f, 0x6f, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x6f, 0x6f, 0x64, 0x12, 0x17, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x46,
	0x6f, 0x6f, 0x64, 0x12, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46,
	0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64,
	0x12, 0x17, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f,
	0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f,
	0x64, 0x12, 0x17, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64,
	0x73, 0x12, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x66, 0x6f, 0x6f, 0x64,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_food_foodpb_food_proto_rawDescOnce sync.Once
	file_food_foodpb_food_proto_rawDescData = file_food_foodpb_food_proto_rawDesc
)

func file_food_foodpb_food_proto_rawDescGZIP() []byte {
	file_food_foodpb_food_proto_rawDescOnce.Do(func() {
		file_food_foodpb_food_proto_rawDescData = protoimpl.X.CompressGZIP(file_food_foodpb_food_proto_rawDescData)
	})
	return file_food_foodpb_food_proto_rawDescData
}

var file_food_foodpb_food_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_food_foodpb_food_proto_goTypes = []interface{}{
	(*Food)(nil),               // 0: data.Food
	(*CreateFoodRequest)(nil),  // 1: data.CreateFoodRequest
	(*CreateFoodResponse)(nil), // 2: data.CreateFoodResponse
	(*ReadFoodRequest)(nil),    // 3: data.ReadFoodRequest
	(*ReadFoodResponse)(nil),   // 4: data.ReadFoodResponse
	(*UpdateFoodRequest)(nil),  // 5: data.UpdateFoodRequest
	(*UpdateFoodResponse)(nil), // 6: data.UpdateFoodResponse
	(*DeleteFoodRequest)(nil),  // 7: data.DeleteFoodRequest
	(*DeleteFoodResponse)(nil), // 8: data.DeleteFoodResponse
	(*ListFoodRequest)(nil),    // 9: data.ListFoodRequest
	(*ListFoodResponse)(nil),   // 10: data.ListFoodResponse
}
var file_food_foodpb_food_proto_depIdxs = []int32{
	0,  // 0: data.CreateFoodRequest.food:type_name -> data.Food
	0,  // 1: data.ReadFoodResponse.food:type_name -> data.Food
	0,  // 2: data.UpdateFoodRequest.food:type_name -> data.Food
	0,  // 3: data.UpdateFoodResponse.food:type_name -> data.Food
	0,  // 4: data.ListFoodResponse.food:type_name -> data.Food
	1,  // 5: data.FoodService.CreateFood:input_type -> data.CreateFoodRequest
	3,  // 6: data.FoodService.ReadFood:input_type -> data.ReadFoodRequest
	5,  // 7: data.FoodService.UpdateFood:input_type -> data.UpdateFoodRequest
	7,  // 8: data.FoodService.DeleteFood:input_type -> data.DeleteFoodRequest
	9,  // 9: data.FoodService.ListFoods:input_type -> data.ListFoodRequest
	2,  // 10: data.FoodService.CreateFood:output_type -> data.CreateFoodResponse
	4,  // 11: data.FoodService.ReadFood:output_type -> data.ReadFoodResponse
	6,  // 12: data.FoodService.UpdateFood:output_type -> data.UpdateFoodResponse
	8,  // 13: data.FoodService.DeleteFood:output_type -> data.DeleteFoodResponse
	10, // 14: data.FoodService.ListFoods:output_type -> data.ListFoodResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_food_foodpb_food_proto_init() }
func file_food_foodpb_food_proto_init() {
	if File_food_foodpb_food_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_food_foodpb_food_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Food); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_foodpb_food_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFoodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_foodpb_food_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFoodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_foodpb_food_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFoodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_foodpb_food_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFoodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_foodpb_food_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFoodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_foodpb_food_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFoodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_foodpb_food_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFoodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_foodpb_food_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFoodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_foodpb_food_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFoodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_foodpb_food_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFoodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_food_foodpb_food_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_food_foodpb_food_proto_goTypes,
		DependencyIndexes: file_food_foodpb_food_proto_depIdxs,
		MessageInfos:      file_food_foodpb_food_proto_msgTypes,
	}.Build()
	File_food_foodpb_food_proto = out.File
	file_food_foodpb_food_proto_rawDesc = nil
	file_food_foodpb_food_proto_goTypes = nil
	file_food_foodpb_food_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FoodServiceClient is the client API for FoodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FoodServiceClient interface {
	CreateFood(ctx context.Context, in *CreateFoodRequest, opts ...grpc.CallOption) (*CreateFoodResponse, error)
	ReadFood(ctx context.Context, in *ReadFoodRequest, opts ...grpc.CallOption) (*ReadFoodResponse, error)
	UpdateFood(ctx context.Context, in *UpdateFoodRequest, opts ...grpc.CallOption) (*UpdateFoodResponse, error)
	DeleteFood(ctx context.Context, in *DeleteFoodRequest, opts ...grpc.CallOption) (*DeleteFoodResponse, error)
	ListFoods(ctx context.Context, opts ...grpc.CallOption) (FoodService_ListFoodsClient, error)
}

type foodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodServiceClient(cc grpc.ClientConnInterface) FoodServiceClient {
	return &foodServiceClient{cc}
}

func (c *foodServiceClient) CreateFood(ctx context.Context, in *CreateFoodRequest, opts ...grpc.CallOption) (*CreateFoodResponse, error) {
	out := new(CreateFoodResponse)
	err := c.cc.Invoke(ctx, "/data.FoodService/CreateFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) ReadFood(ctx context.Context, in *ReadFoodRequest, opts ...grpc.CallOption) (*ReadFoodResponse, error) {
	out := new(ReadFoodResponse)
	err := c.cc.Invoke(ctx, "/data.FoodService/ReadFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) UpdateFood(ctx context.Context, in *UpdateFoodRequest, opts ...grpc.CallOption) (*UpdateFoodResponse, error) {
	out := new(UpdateFoodResponse)
	err := c.cc.Invoke(ctx, "/data.FoodService/UpdateFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) DeleteFood(ctx context.Context, in *DeleteFoodRequest, opts ...grpc.CallOption) (*DeleteFoodResponse, error) {
	out := new(DeleteFoodResponse)
	err := c.cc.Invoke(ctx, "/data.FoodService/DeleteFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) ListFoods(ctx context.Context, opts ...grpc.CallOption) (FoodService_ListFoodsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FoodService_serviceDesc.Streams[0], "/data.FoodService/ListFoods", opts...)
	if err != nil {
		return nil, err
	}
	x := &foodServiceListFoodsClient{stream}
	return x, nil
}

type FoodService_ListFoodsClient interface {
	Send(*ListFoodRequest) error
	Recv() (*ListFoodResponse, error)
	grpc.ClientStream
}

type foodServiceListFoodsClient struct {
	grpc.ClientStream
}

func (x *foodServiceListFoodsClient) Send(m *ListFoodRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *foodServiceListFoodsClient) Recv() (*ListFoodResponse, error) {
	m := new(ListFoodResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FoodServiceServer is the server API for FoodService service.
type FoodServiceServer interface {
	CreateFood(context.Context, *CreateFoodRequest) (*CreateFoodResponse, error)
	ReadFood(context.Context, *ReadFoodRequest) (*ReadFoodResponse, error)
	UpdateFood(context.Context, *UpdateFoodRequest) (*UpdateFoodResponse, error)
	DeleteFood(context.Context, *DeleteFoodRequest) (*DeleteFoodResponse, error)
	ListFoods(FoodService_ListFoodsServer) error
}

// UnimplementedFoodServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFoodServiceServer struct {
}

func (*UnimplementedFoodServiceServer) CreateFood(context.Context, *CreateFoodRequest) (*CreateFoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFood not implemented")
}
func (*UnimplementedFoodServiceServer) ReadFood(context.Context, *ReadFoodRequest) (*ReadFoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFood not implemented")
}
func (*UnimplementedFoodServiceServer) UpdateFood(context.Context, *UpdateFoodRequest) (*UpdateFoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFood not implemented")
}
func (*UnimplementedFoodServiceServer) DeleteFood(context.Context, *DeleteFoodRequest) (*DeleteFoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFood not implemented")
}
func (*UnimplementedFoodServiceServer) ListFoods(FoodService_ListFoodsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFoods not implemented")
}

func RegisterFoodServiceServer(s *grpc.Server, srv FoodServiceServer) {
	s.RegisterService(&_FoodService_serviceDesc, srv)
}

func _FoodService_CreateFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).CreateFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.FoodService/CreateFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).CreateFood(ctx, req.(*CreateFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_ReadFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).ReadFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.FoodService/ReadFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).ReadFood(ctx, req.(*ReadFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_UpdateFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).UpdateFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.FoodService/UpdateFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).UpdateFood(ctx, req.(*UpdateFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_DeleteFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).DeleteFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.FoodService/DeleteFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).DeleteFood(ctx, req.(*DeleteFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_ListFoods_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FoodServiceServer).ListFoods(&foodServiceListFoodsServer{stream})
}

type FoodService_ListFoodsServer interface {
	Send(*ListFoodResponse) error
	Recv() (*ListFoodRequest, error)
	grpc.ServerStream
}

type foodServiceListFoodsServer struct {
	grpc.ServerStream
}

func (x *foodServiceListFoodsServer) Send(m *ListFoodResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *foodServiceListFoodsServer) Recv() (*ListFoodRequest, error) {
	m := new(ListFoodRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FoodService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.FoodService",
	HandlerType: (*FoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFood",
			Handler:    _FoodService_CreateFood_Handler,
		},
		{
			MethodName: "ReadFood",
			Handler:    _FoodService_ReadFood_Handler,
		},
		{
			MethodName: "UpdateFood",
			Handler:    _FoodService_UpdateFood_Handler,
		},
		{
			MethodName: "DeleteFood",
			Handler:    _FoodService_DeleteFood_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFoods",
			Handler:       _FoodService_ListFoods_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "food/foodpb/food.proto",
}
